### ISSUE TITLE
Invalid command including arguments

### ISSUE THREAD

**Issue by alxping** [robertdebock/ansible-role-service#3]
According to the way `start_command` is defined in sysvinit, a command with arguments is not executed properly.

https://github.com/robertdebock/ansible-role-service/blob/3285b2843d0c6c220d9c247970150542afaea040/templates/sysvinit.j2#L35

For example, the ansible role `robertdebock.etherpad` provides the following variable used by `robertdebock.service`:
```yaml
service_list:
  - name: etherpad
    description: Etherpad
    start_command: "{{ etherpad_working_directory }}/bin/run.sh --root"
    working_directory: "{{ etherpad_working_directory }}"
```

I guess the quotes in template `sysvinit.j2` shall be removed.
